name: test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
    services:
      spanner:
        image: gcr.io/cloud-spanner-emulator/emulator
        ports:
          - 9010:9010
    env:
      SPANNER_EMULATOR_HOST: localhost:9010

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

    - uses: codecov/codecov-action@v4
      with:
        files: coverage/coverage.xml
